#!/bin/bash

# ls
if [[ FreeBSD == $(uname) || Darwin == $(uname) ]] ; then
    alias ls='ls -GF'
    alias ll='ls -lk'
else
    # enable color support of ls and also add handy aliases
    if [ -x /usr/bin/dircolors ]; then
        test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
        alias ls='ls --color=auto'
        #alias dir='dir --color=auto'
        #alias vdir='vdir --color=auto'

    fi
    alias ls='ls -F --color'
    alias ll='ls -l'
fi
alias ll='ls -l'
alias la='ll -a'
alias l.="ls -d .*"
alias l='ls'


alias grep='grep --color=auto'
alias cgrep='grep --color=always'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'


alias cd..="cd .."
alias s="cd .."
alias p="cd -"
alias md="mkdir"
alias rd="rmdir"
alias cp="cp -i"
alias mv="mv -i"
alias c=clear

# JSON Tidy
alias jsontidy='\python -m json.tool'

# Attach to a screen session and detach it elsewhere if need be.
alias screen='screen -dR'

calc(){ awk "BEGIN{ print $* }" ;}

alias g=git
alias gs='g st'
alias gch='g checkout'

# View HTTP traffic
alias sniff="sudo ngrep -d 'en1' -t '^(GET|POST) ' 'tcp and port 80'"
alias httpdump="sudo tcpdump -i en1 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""

# Enhanced WHOIS lookups
alias whois="whois -h whois-servers.net"

# OS X has no `md5sum`, so use `md5` as a fallback
type -t md5sum > /dev/null || alias md5sum="md5"

# Recursively delete `.DS_Store` files
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"

# Cleanup the "Open With" menu
alias fixopenwith='/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user'

# Show most used commands
mostusedf() {
    history | awk '{a[$2]++ } END{for(i in a){print a[i] " " i}}' | sort -rn | head -n 20
}
alias mostused=mostusedf

# File size
alias fs="stat -f \"%z bytes\""

# ROT13-encode text. Works for decoding, too! ;)
alias rot13='tr a-zA-Z n-za-mN-ZA-M'

# Empty the Trash on all mounted volumes and the main HDD
# Also, clear Apple’s System Logs to improve shell startup speed
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl"

# Hide/show all desktop icons (useful when presenting)
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

# Disable Spotlight
alias spotoff="sudo mdutil -a -i off"
# Enable Spotlight
alias spoton="sudo mdutil -a -i on"

# Stuff I never really use but cannot delete either because of http://xkcd.com/530/
alias stfu="osascript -e 'set volume output muted true'"
alias pumpitup="osascript -e 'set volume 10'"



: ${UNAME=$(uname)}

alias xmltidy='xmllint --format'

if [ "$UNAME" = Darwin ]; then
    alias ls='ls -GF'
    alias ll='ls -lk'

    test -e '/Applications/MacVim.app' &&
    alias gvim='open -a /Applications/MacVim.app'

    if hash hub 2>/dev/null; then
        alias git=hub
    fi

    alias subl='subl -n'
    alias sub=subl
    alias mate=subl

    ## Educreations Apps
    alias ios='cd ~/dev/edu/ios'
    alias www='workon www'
fi

alias essh='awsactivate educreations && ec2-ssh'
alias ehost='awsactivate educreations && ec2-host'

alias lsvirtualenv='lsvirtualenv -b'
