#!/bin/sh

# ----------------------------------------------------------------------
# PROMPT
# ----------------------------------------------------------------------

BOLD="\[$(tput bold)\]"
RED="\[$(tput setaf 1)\]"
GREEN="\[$(tput setaf 2)\]"
YELLOW="\[$(tput setaf 3)\]"
BLUE="\[$(tput setaf 4)\]"
MAGENTA="\[$(tput setaf 5)\]"
CYAN="\[$(tput setaf 6)\]"
WHITE="\[$(tput setaf 7)\]"
NORMAL="\[$(tput sgr0)\]"
SCREEN_ESC="\[\033k\033\134\]"

if [ "$LOGNAME" = "root" ]; then
    COLOR1="${RED}"
    COLOR2="${WHITE}"
    P="#"
else
    COLOR1="${YELLOW}"
    COLOR2="${RED}"
    #P="⚡"
    P="$"
fi

# Get the Git branch
parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

# Virtualenv
parse_virtualenv () {
    if test -z "$VIRTUAL_ENV"; then
        echo -n ""
    else
        basename "$VIRTUAL_ENV" | sed -e 's/\(.*\)/ (\1)/'
    fi
}

prompt_simple() {
    unset PROMPT_COMMAND
    PS1="[\u@\h:\w]\$ "
    PS2="> "
}

prompt_compact() {
    unset PROMPT_COMMAND
    PS1="${COLOR1}${P}${NORMAL} "
    PS2="> "
}

prompt_color() {
    PS1="\n${NORMAL}${COLOR1}➜ ${COLOR2}\w${CYAN}\$(parse_virtualenv)${YELLOW}\$(parse_git_branch) ${NORMAL}"
    PS2="${WHITE}continue> ${NORMAL}"

    test -n "$PS1" &&
    PROMPT_COMMAND='echo -ne "\033]0;${HOSTNAME}\007"'
    fun=`type -t update_terminal_cwd`
    if [ "$fun" == "function" ]; then
        PROMPT_COMMAND="update_terminal_cwd; $PROMPT_COMMAND"
    fi
}
