#!/bin/bash
# .bash_profile
umask 002

if [ -f /etc/profile ]; then
        source /etc/profile
fi


if [ -f /opt/local/environment/.bash_profile ]; then
	source /opt/local/environment/.bash_profile
fi

if [ -f ~/.bashrc ]; then
	source ~/.bashrc
fi

test -r /sw/bin/init.sh && . /sw/bin/init.sh

# MacPorts Addition
if [ -e /opt ]; then
    export PATH=/opt/local/bin:/opt/local/sbin:$PATH
    export MANPATH=/opt/local/share/man:$MANPATH
fi

