# .bash_profile
umask 002

if [ -f /etc/profile ]; then
        source /etc/profile
fi


if [ -f /opt/local/environment/.bash_profile ]; then
	source /opt/local/environment/.bash_profile
fi

if [ -f ~/.bashrc ]; then
	source ~/.bashrc
fi

export DISPLAY=:0.0
export LESS='-X -e'
export PAGER=less

# Completions are critical in interactive shells:
#BASH_COMP_SP="/etc /usr/local/etc /opt/local/etc"
#for conf_dir in $BASH_COMP_SP ; do
#        if [ -f "$conf_dir/bash_completion" ] && [ -z "$BASH_COMPLETION" ] ; then               
#                source "$conf_dir/bash_completion"
#        fi
#done

test -r /sw/bin/init.sh && . /sw/bin/init.sh

# MacPorts Addition
if [ -e /opt ]; then
    export PATH=/opt/local/bin:/opt/local/sbin:$PATH
    export MANPATH=/opt/local/share/man:$MANPATH
fi

if [ -e ~/.ec2 ]; then
    export EC2_HOME=~/.ec2
    export PATH=$PATH:$EC2_HOME/bin
    export EC2_PRIVATE_KEY=`ls $EC2_HOME/pk-*.pem`
    export EC2_CERT=`ls $EC2_HOME/cert-*.pem`
    export EC2_KEYPAIR_US_EAST_1=$EC2_HOME/ec2-keypair-us-east-1
    export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Home/
fi
