#!/bin/bash
# Configure the bash environment
#
# Chris Streeter <http://www.chrisstreeter.com>

# Debug slow startup
#set -x

# setup some basic variables
: ${HOME=~}
: ${LOGNAME=$(id -un)}
: ${UNAME=$(uname)}

# ----------------------------------------------------------------------
# CONFIGURATION
# ----------------------------------------------------------------------

# complete hostnames from
: ${HOSTFILE=~/.ssh/known_hosts}

# ----------------------------------------------------------------------
#  SHELL OPTIONS
# ----------------------------------------------------------------------

# Source global definitions
[ -f /etc/bashrc ] && source /etc/bashrc
[ -f /etc/bash.bashrc ] && source /etc/bash.bashrc
[ -f /rc/etc/dotfiles/system.bashrc ] && source /rc/etc/dotfiles/system.bashrc

# notify of bg job completion immediately
set -o notify

# shell opts. see bash(1) for details
shopt -s extglob >/dev/null 2>&1
shopt -s hostcomplete >/dev/null 2>&1
shopt -s interactive_comments >/dev/null 2>&1
shopt -u mailwarn >/dev/null 2>&1
shopt -s no_empty_cmd_completion >/dev/null 2>&1

# Autocorrect typos in path names when using `cd`
shopt -s cdspell >/dev/null 2>&1

# append to the history file, don't overwrite it
shopt -s histappend

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

# fuck that you have new mail shit
unset MAILCHECK

# default umask (mask out permissions on new files)
umask 0022

# ----------------------------------------------------------------------
# PATH
# ----------------------------------------------------------------------

# we want the various sbins on the path along with /usr/local/bin
PATH="/usr/local/bin:$PATH:/usr/local/sbin:/usr/sbin:/sbin"

test -d "$HOME/bin" &&
    PATH="$HOME/bin:$PATH"

test -d "/usr/local/share/npm/bin" &&
    PATH="$PATH:/usr/local/share/npm/bin"

export PATH

# ----------------------------------------------------------------------
# ENVIRONMENT CONFIGURATION
# ----------------------------------------------------------------------

# detect interactive shell
case "$-" in
    *i*) INTERACTIVE=1 ;;
    *)   unset INTERACTIVE ;;
esac

# detect login shell
case "$0" in
    -*) LOGIN=1 ;;
    *)  unset LOGIN ;;
esac

# enable en_US locale w/ utf-8 encodings if not already configured
: ${LANG:="en_US"}
: ${LANGUAGE:="en"}
: ${LC_CTYPE:="en_US.UTF-8"}
: ${LC_ALL:="en_US.UTF-8"}
export LANG LANGUAGE LC_CTYPE LC_ALL

# ignore backups, CVS directories, python bytecode, vim swap files
FIGNORE="~:CVS:#:.pyc:.swp:.swa"


# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"



# ----------------------------------------------------------------------
# MACOS X / DARWIN SPECIFIC
# ----------------------------------------------------------------------

if [ "$UNAME" = Darwin ]; then
    test -x /usr/pkg && {
        PATH="/usr/pkg/sbin:/usr/pkg/bin:$PATH"
        MANPATH="/usr/pkg/share/man:$MANPATH"
    }
fi

# ----------------------------------------------------------------------
# BASH COMPLETION
# ----------------------------------------------------------------------

if test -z "$BASH_COMPLETION" ; then
    bash=${BASH_VERSION%.*}; bmajor=${bash%.*}; bminor=${bash#*.}
    if [ "$PS1" ] && [ $bmajor -gt 1 ] ; then
        # search for a bash_completion file to source
        for f in /usr/pkg/etc/back_completion \
            /usr/local/etc/bash_completion \
            /etc/bash_completion \
            ~/.bash_completion ;
        do
            test -f $f && {
                . $f
                break
            }
        done
    fi
    unset bash bmajor bminor
fi

# override and disable tilde expansion
_expand() {
    return 0
}

# ----------------------------------------------------------------------
# PYTHON STARTUP / AUTO-COMPLETION
# ----------------------------------------------------------------------
if test -e "$HOME/.pystartup"; then
    export PYTHONSTARTUP="$HOME/.pystartup"
fi

# ----------------------------------------------------------------------
# LS AND DIRCOLORS
# ----------------------------------------------------------------------

# we always pass these to ls(1)
LS_COMMON="-BG"

# if the dircolors utility is available, set that up to
dircolors="$(type -P gdircolors dircolors | head -1)"
test -n "$dircolors" && {
    COLORS=/etc/DIR_COLORS
    test -e "/etc/DIR_COLORS.$TERM"   && COLORS="/etc/DIR_COLORS.$TERM"
    test -e "$HOME/.dircolors"        && COLORS="$HOME/.dircolors"
    test ! -e "$COLORS"               && COLORS=
    eval `$dircolors --sh $COLORS`
}
unset dircolors

# setup the main ls alias if we've established common args
test -n "$LS_COMMON" &&
alias ls="command ls $LS_COMMON"


# -------------------------------------------------------------------
# EXPORTS
# -------------------------------------------------------------------

test -f "$HOME/.exports" &&
source "$HOME/.exports"


# -------------------------------------------------------------------
# PROMPT
# -------------------------------------------------------------------

test -f "$HOME/.bash_prompt" &&
source "$HOME/.bash_prompt"

# -------------------------------------------------------------------
# USER SHELL ENVIRONMENT
# -------------------------------------------------------------------

# Use the color prompt by default when interactive
test -n "$PS1" &&
prompt_color

# -------------------------------------------------------------------
# MOTD / FORTUNE
# -------------------------------------------------------------------

#test -n "$INTERACTIVE" -a -n "$LOGIN" && {
#    uname -npsr
#    uptime
#}

# ----------------------------------------------------------------------
# ALIASES / FUNCTIONS
# ----------------------------------------------------------------------

# User specific aliases and functions
test -f "$HOME/.alias" &&
source "$HOME/.alias"

test -f "$HOME/.functions" &&
source "$HOME/.functions"

# -------------------------------------------------------------------
# MACHINE SPECIFIC BASHRC
# -------------------------------------------------------------------

BASHRC_DIR="$HOME/.bashrc.d"
test -d "$BASHRC_DIR" &&
test -e "$BASHRC_DIR/$HOSTNAME.bashrc" &&
source "$BASHRC_DIR/$HOSTNAME.bashrc"

# -------------------------------------------------------------------
# USER SPECIFIC BASHRC
# -------------------------------------------------------------------

test -d "$BASHRC_DIR" &&
test -e "$BASHRC_DIR/$USER.bashrc" &&
source "$BASHRC_DIR/$USER.bashrc"
unset BASHRC_DIR

# -------------------------------------------------------------------
# MACHINE SPECIFIC ALIASES
# -------------------------------------------------------------------

ALIAS_DIR="$HOME/.alias.d"
test -d "$ALIAS_DIR" &&
test -e "$ALIAS_DIR/$HOSTNAME.alias" &&
source "$ALIAS_DIR/$HOSTNAME.alias"

# -------------------------------------------------------------------
# USER SPECIFIC ALIASES
# -------------------------------------------------------------------

test -d "$ALIAS_DIR" &&
test -e "$ALIAS_DIR/$USER.alias" &&
source "$ALIAS_DIR/$USER.alias"
unset ALIAS_DIR

# -------------------------------------------------------------------
# POST CONFIGURATION HOOKS
# -------------------------------------------------------------------

# Python virtualenvwrapper Setup
export WORKON_HOME=$HOME/.virtualenvs
export PIP_VIRTUALENV_BASE=$WORKON_HOME
export PIP_DOWNLOAD_CACHE=$HOME/.pip-cache

if [ -e "${HOME}/.bashrc.d/virtualenvwrapper.bashrc" ]; then
    source "${HOME}/.bashrc.d/virtualenvwrapper.bashrc"
fi

# Autoenv
AUTOENV_ACTIVATE='/usr/local/Cellar/autoenv/0.1.0/activate.sh'
test -e $AUTOENV_ACTIVATE &&
source $AUTOENV_ACTIVATE
unset AUTOENV_ACTIVATE

# vim: ts=4 sts=4 shiftwidth=4 expandtab

# added by travis gem
source /Users/streeter/.travis/travis.sh
