#!/bin/sh

# ----------------------------------------------------------------------
# PAGER / EDITOR
# ----------------------------------------------------------------------

# See what we have to work with ...
HAVE_VIM=$(command -v vim)
HAVE_GVIM=$(command -v gvim)

# EDITOR
test -n "$HAVE_VIM" &&
EDITOR=vim ||
EDITOR=vi
export EDITOR

# PAGER
if test -n "$(command -v less)" ; then
    PAGER="less -FirSwX"
    MANPAGER="less -FiRswX"
    export LESS="-R -e"
else
    PAGER=more
    MANPAGER="$PAGER"
fi
export PAGER MANPAGER

# Highlight section titles in manual pages
export LESS_TERMCAP_md="$ORANGE"


# ----------------------------------------------------------------------
# HISTORY
# ----------------------------------------------------------------------

# don't put duplicate lines in the history. See bash(1) for more options
#export HISTCONTROL=$HISTCONTROL${HISTCONTROL+:}ignoredups
# ... or force ignoredups and ignorespace or ignoreboth
export HISTCONTROL=ignoredups

# Make some commands not show up in history
export HISTIGNORE="ls:ls *:cd:cd -:pwd;exit:date:* --help"

export HISTSIZE=200000
export HISTFILESIZE=$HISTSIZE

