#!/bin/bash
# This hook is run after every virtualenv is activated.

if [[ ! -e "${VIRTUAL_ENV}/.project" ]]; then
    echo "Setting up virtualenvproject..."
    setvirtualenvproject
fi

__env_file="$(cat "${VIRTUAL_ENV}/.project")/.env"
if [[] ! -e "${__env_file}" ]]; then
    echo "Creating ${__env_file}"
    cat > "${__env_file}" <<EOF
#!/bin/bash
case \$VIRTUAL_ENV in
    *\\${VIRTUAL_ENV##*/})
        ;;
    *)
        workon \\${VIRTUAL_ENV##*/}
        ;;
esac
EOF
    autoenv_authorize_env "${__env_file}"
fi
unset __env_file
