#!/bin/bash
# This hook is run after a new virtualenv is created

# The following will set up a .project link so that when `workon <venv>` is
# called, we automatically cd to that directory.
#if [[ ! -e "${VIRTUAL_ENV}/.project" ]]; then
#    echo "Setting up virtualenvproject..."
#    setvirtualenvproject
#fi

__env_file="${PWD}/.env"
if [[ ! -e "${__env_file}" ]]; then
    echo "Creating ${__env_file}"
    cat > "${__env_file}" <<EOF
#!/bin/bash
case \$VIRTUAL_ENV in
    *\\${VIRTUAL_ENV##*/})
        ;;
    *)
        workon ${VIRTUAL_ENV##*/}
        ;;
esac
EOF
    autoenv_authorize_env "${__env_file}"
fi
unset __env_file
