#!/bin/bash
# This hook is run after every virtualenv is activated.

# Sign python so we don't get warnings all the time
if which -s codesign; then
    codesign -v `which python` || codesign -s - `which python`
fi
